### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by nhi-dang-by** [Azure-Samples/azure-maps-animations#1]
> Please provide us with the following information:
> ---------------------------------------------------------------
Would be great if this project can be published to npm
Hard to include it to our project with the current package

**Comment by PawelStadnicki** [comment]
Yes, please add to npm

**Comment by markphillips100** [comment]
Any likelihood this will make it to a CDN also, like the main atlas.min.js and atlas-indoor.min.js files?

My use case requires script tag access to these files via https.  I cannot use an npm package or any local file as I'm embedding the html in a Flutter WebView widget that only supports local "assets" for the main html file, not script references.

I guess I can copy the file to my own server host and serve from there but would hope these atlas extensions would make it to a CDN one day.

**Comment by cbonnaud001** [comment]
Hello, it's been a year and still no update on the subject. 
It's a bit sad to see such a big Microsoft product having no real support for modern application (typescript, complete npm packages, SPA modules integration, etc)

**Comment by TorstenL** [comment]
Yes a NPM Package would be awesome.

**Comment by dubiety** [comment]
Hi @nhi-dang-by , @PawelStadnicki, @cbonnaud001 , @TorstenL, @markphillips100,

Thank you for the great suggestion! We'll start working on NPM module as well as CDN endpoint within the following months. I'll notify you once it is done.

**Comment by zhz0704** [comment]
Hi @nhi-dang-by, @PawelStadnicki, @cbonnaud001, @TorstenL, @markphillips100,

Thank you for your patience. We've published the NPM module: https://www.npmjs.com/package/@azure-maps/animations
