### ISSUE TITLE
Changing map styles while animation is playing (weather) causes JS error

### ISSUE THREAD

**Issue by PedroBuhigas** [Azure-Samples/azure-maps-animations#2]
ncaught (in promise) TypeError: i[t]._getSourceIds is not a function
    at sm._getSourceIds (atlas.min.js:55)
    at atlas.min.js:55
sm._getSourceIds @ atlas.min.js:55
(anonymous) @ atlas.min.js:55
Promise.then (async)
hg._setStyleComponents @ atlas.min.js:55
hg.setStyle @ atlas.min.js:55
updateMapType @ Index.html:287
onchange @ Index.html:471
ListPicker._handleMouseUp

**Comment by rbrundritt** [comment]
I'm unable to reproduce this. It's possible it might be related to issue #4
