### ISSUE TITLE
No Support for Angular

### ISSUE THREAD

**Issue by anmol-Git** [Azure-Samples/azure-maps-animations#3]
Hi , I was trying to make an delivery application using azure maps but got stuck as there is no Animation module in azure-map-control . 
I tried to go for any alternative but not found any. 
This repo need its npm package so that it can be use by different frameworks

**Comment by dubiety** [comment]
Hi @anmol-Git,

Sorry for the late reply. We'll support npm package and CDN endpoint in the following months. Will notify you once it's done!

**Comment by zhz0704** [comment]
Hi @anmol-Git,

Thank you for your patience. We've published the NPM module: https://www.npmjs.com/package/@azure-maps/animations
