### ISSUE TITLE
AnimatedTileLayer causes a crash when map is disposed

### ISSUE THREAD

**Issue by Xellon** [Azure-Samples/azure-maps-animations#4]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Open Animated Tile Layer sample https://azuremapscodesamples.azurewebsites.net/Animations/Animated%20tile%20layer.html
2. Type `map.dispose()` in the browser console

### Any log messages given by the failure
```
Uncaught TypeError: Cannot read properties of undefined (reading '_getLayerIds')
    at og._removeMapboxLayers (atlas.min.js:55)
    at og.clear (atlas.min.js:55)
    at sv.clear (atlas.min.js:55)
    at sv.dispose (atlas.min.js:55)
    at <anonymous>:1:5
```

### Expected/desired behavior
> Disposing map with an animated tile layer should not crash the map

### OS and Version?
> Windows 10.

### Versions
> Any

### Mention any other details that might be useful

> Using map with React and we dispose it when component containing map is unmounted.

**Comment by rbrundritt** [comment]
Not sure how to fix this just yet, but a simple workaround is to remove the animated layer before disposing the map.

```
map.layers.remove(layer);
map.dispose();
```

**Comment by rbrundritt** [comment]
Managed to come up with a fix for this. Get the latest code from the dist folder.
